[deta]
DETA_KEY = 'c0mzakyewnf_Mewb5QYoVe86SFcbWWKcuRBYKSyqaAoQ'


[naver_sms]
access_key = "yIPYkieg4sRxCMEiBFpV"				# access key id (from portal or Sub Account)
secret_key = "3yjiE9UtkduzXfauOKCi2lBBVmSA7HkS8tiZytm4"				# secret key (from portal or Sub Account)


[telegram]
hojin_token = '849024464:AAFdq6iDBMU4V39Yf3w8SCoBZhv_VtW1PsU'
